Style/MultilineMethodCallIndentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Exclude:
    - 'vendor/**/*'
    - 'spec/support/*.rb'
    - '*.gemspec'

Documentation:
  Enabled: false
